### ISSUE TITLE
correct use of parentheses in exclusion statements

### ISSUE THREAD

**Issue by teleaslamellatus** [hymao/hymao-data#2]
@balhoff 

verbatime:
antenna except scape yellow

version a:
('has part' some ((not (pedicel)) and (part_of some antenna) and ('bearer of' some brown)))

or

('has part' some ((not (pedicel)) and (part_of some antenna and ('bearer of' some brown))))

I think in the second version means the antenna is brown.

**Comment by balhoff** [comment]
What about this?

`'has part' some (antenna and 'has part' some ((not pedicel) and 'bearer of' some brown))`

You mean all of the antenna is brown except for the pedicel?

**Comment by teleaslamellatus** [comment]
Yes! Thanks Jim!
